In [4]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [5]:
url = 'https://www.eia.gov/electricity/wholesale/'
r = requests.get(url)
print(r)

<Response [200]>

In [9]:
soup = BeautifulSoup(r.content)
links = soup.find_all('a')
print(len(links))

253

In [21]:
pwr_links = []
for i in links:
    if 'href' in str(i):
        l = i['href']
        if ('elec' in l) & ('.xls' in l):
            pwr_links.append(l)
pwr_links

['xls/ice_electric-2021.xlsx',
 'xls/archive/ice_electric-2020final.xlsx',
 'xls/archive/ice_electric-2019final.xlsx',
 'xls/archive/ice_electric-2018final.xlsx',
 'xls/archive/ice_electric-2017final.xlsx',
 'xls/archive/ice_electric-2016final.xls',
 'xls/archive/ice_electric-2015final.xls',
 'xls/archive/ice_electric-2014final.xls']

In [31]:
test = pd.read_excel(url + pwr_links[0], sheet_name=0)
test.head()

,Price hub,Trade date,Delivery start date,Delivery \nend date,High price $/MWh,Low price $/MWh,Wtd avg price $/MWh,Change,Daily volume MWh,Number of trades,Number of counterparties
0,Indiana Hub RT Peak,2021-01-07,2021-01-08,2021-01-08,35.0,32.6,33.62,1.68,12000,14,10
1,Indiana Hub RT Peak,2021-01-12,2021-01-13,2021-01-13,29.5,28.5,29.00,-4.62,1600,2,3
2,Indiana Hub RT Peak,2021-01-21,2021-01-22,2021-01-22,27.0,26.5,26.75,-2.25,1600,2,3
3,Indiana Hub RT Peak,2021-01-26,2021-01-27,2021-01-27,30.0,30.0,30.00,3.25,5600,5,5
4,Indiana Hub RT Peak,2021-02-04,2021-02-05,2021-02-05,30.5,30.5,30.50,0.50,3200,3,4

In [41]:
data = []
for p in pwr_links:
    print(p)
    df = pd.read_excel(url + p, sheet_name=0)
    data.append(df)
data = pd.concat(data)
data.head()

xls/ice_electric-2021.xlsx
xls/archive/ice_electric-2020final.xlsx
xls/archive/ice_electric-2019final.xlsx
xls/archive/ice_electric-2018final.xlsx
xls/archive/ice_electric-2017final.xlsx
xls/archive/ice_electric-2016final.xls
xls/archive/ice_electric-2015final.xls
xls/archive/ice_electric-2014final.xls

,Price hub,Trade date,Delivery start date,Delivery \nend date,High price $/MWh,Low price $/MWh,Wtd avg price $/MWh,Change,Daily volume MWh,Number of trades,Number of counterparties
0,Indiana Hub RT Peak,2021-01-07,2021-01-08,2021-01-08,35.0,32.6,33.62,1.68,12000,14,10
1,Indiana Hub RT Peak,2021-01-12,2021-01-13,2021-01-13,29.5,28.5,29.00,-4.62,1600,2,3
2,Indiana Hub RT Peak,2021-01-21,2021-01-22,2021-01-22,27.0,26.5,26.75,-2.25,1600,2,3
3,Indiana Hub RT Peak,2021-01-26,2021-01-27,2021-01-27,30.0,30.0,30.00,3.25,5600,5,5
4,Indiana Hub RT Peak,2021-02-04,2021-02-05,2021-02-05,30.5,30.5,30.50,0.50,3200,3,4

In [42]:
data.columns = data.columns.str.lower().str.replace(' ', '_').str.replace('\n', '')
data.columns.tolist()

['price_hub',
 'trade_date',
 'delivery_start_date',
 'delivery_end_date',
 'high_price_$/mwh',
 'low_price_$/mwh',
 'wtd_avg_price_$/mwh',
 'change',
 'daily_volume_mwh',
 'number_of_trades',
 'number_of_counterparties']

In [45]:
data['price_hub'].sort_values().unique().tolist() # notice misalignment of 2 pjm WH

['ERCOT North 345KV Peak',
 'Indiana Hub RT Peak',
 'Indiana Rt Peak',
 'Mid C Peak',
 'Mid Columbia Peak',
 'NP 15 EZ Gen DA LMP Peak',
 'NP15 EZ Gen DA LMP Peak',
 'Nepool MH DA LMP Peak',
 'Nepool MH Da LMP Peak',
 'PJM WH Real Time Peak',
 'PJM-Wh Real Time Peak',
 'Palo Verde',
 'Palo Verde Peak',
 'SP-15 Gen DA LMP Peak',
 'SP15 EZ Gen DA LMP Peak']

In [46]:
data['price_hub'] = data['price_hub'].replace('PJM-Wh Real Time Peak', 'PJM WH Real Time Peak')

In [47]:
data['price_hub'].sort_values().unique().tolist()

['ERCOT North 345KV Peak',
 'Indiana Hub RT Peak',
 'Indiana Rt Peak',
 'Mid C Peak',
 'Mid Columbia Peak',
 'NP 15 EZ Gen DA LMP Peak',
 'NP15 EZ Gen DA LMP Peak',
 'Nepool MH DA LMP Peak',
 'Nepool MH Da LMP Peak',
 'PJM WH Real Time Peak',
 'Palo Verde',
 'Palo Verde Peak',
 'SP-15 Gen DA LMP Peak',
 'SP15 EZ Gen DA LMP Peak']

In [48]:
pjm = data[data['price_hub'] == 'PJM WH Real Time Peak']
pjm

,price_hub,trade_date,delivery_start_date,delivery_end_date,high_price_$/mwh,low_price_$/mwh,wtd_avg_price_$/mwh,change,daily_volume_mwh,number_of_trades,number_of_counterparties
627,PJM WH Real Time Peak,2020-12-30,2020-12-31,2020-12-31,20.75,20.00,20.350000,-2.53,8800,11,9
628,PJM WH Real Time Peak,2020-12-31,2021-01-04,2021-01-04,23.50,23.25,23.380000,3.03,1600,2,4
629,PJM WH Real Time Peak,2021-01-04,2021-01-05,2021-01-05,28.85,25.00,27.210000,3.83,43200,53,27
630,PJM WH Real Time Peak,2021-01-05,2021-01-06,2021-01-06,35.50,33.25,34.420000,7.21,28000,33,26
631,PJM WH Real Time Peak,2021-01-06,2021-01-07,2021-01-07,28.25,27.10,27.840000,-6.58,14400,18,14
...,...,...,...,...,...,...,...,...,...,...,...
1567,PJM WH Real Time Peak,2014-04-07,2014-04-08,2014-04-08,46.00,44.75,45.626923,-3.83,62400,75,40
1568,PJM WH Real Time Peak,2014-04-08,2014-04-09,2014-04-09,43.75,42.75,43.424324,-2.21,29600,37,22
1569,PJM WH Real Time Peak,2014-04-09,2014-04-10,2014-04-10,39.50,37.75,38.388182,-5.03,44000,55,28
1570,PJM WH Real Time Peak,2014-04-10,2014-04-11,2014-04-11,37.25,36.75,36.950000,-1.44,17600,22,21
1571,PJM WH Real Time Peak,2014-04-11,2014-04-14,2014-04-14,45.75,41.00,43.072656,6.12,51200,61,26

In [50]:
pjm = pjm[['delivery_start_date',
           'wtd_avg_price_$/mwh',
           'high_price_$/mwh',
           'low_price_$/mwh',]]
pjm.columns = ['date', 'price', 'high', 'low']

In [53]:
pjm['date'] = pd.to_datetime(pjm['date'])
pjm = pjm.sort_values('date')

C:\Users\Josh\anaconda3\envs\purebirth\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [57]:
import os
if not os.path.exists('data'):
    os.mkdir('data')
pjm.to_csv('data/pjm_power_px.csv', index=False)